[workspace]
members = [
    "crates/monban-cli",
    "crates/monban-core",
    "crates/monban-parser",
]
resolver = "3"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
indexmap = "2.13"
lindera = { version = "2.2.0", features = ["embed-ipadic"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
