[package]
name = "monban-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
epub = { workspace = true }
lindera = { workspace = true }
monban-core = { path = "../monban-core/" }
serde_json = { workspace = true }
tracing = { workspace = true }
