[dictionary]
words = "data/dict/jmdict.json"
kanji = "data/dict/kanji.json"

[parser]
dictionary = "embedded://ipadic"

[parser.filtering]
exclude_chars = ["ー", "〜"]

[parser.filtering.include]
"名詞" = ["一般", "サ変接続"]
"動詞" = ["自立"]
"感動詞" = ["*"]

[decks]
"kaishi" = { file="data/decks/kaishi.txt", type="plain" }
"wk" = { file="data/decks/wk.json", type="wk" }
"jlpt" = { file="data/decks/jlpt.json", type="jlpt" }

