[package]
name = "monban-core"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
